# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "cloudsensei-terraform-state-681528281969"
    encrypt = true
    key     = "./terraform.tfstate"
    region  = "eu-central-1"
  }
}
