# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_version = ">= 1.0"
}

provider "aws" {
  region = "eu-central-1"

  default_tags {
    tags = {
      Project     = "cloudsensei"
      Environment = "management"
      ManagedBy   = "terragrunt"
    }
  }
}
