apiVersion: cloudsensei.cloud-sensei.com/v1alpha1
kind: CloudSenseiCollector
metadata:
  name: my-collector
spec:
  sources:
    - type: metrics
      provider: prometheus
      scrapeInterval: 30s
      endpoints:
        - http://prometheus-operated:9090
      metrics:
        include:
          - cpu_usage_seconds_total
          - http_requests_total
        exclude:
          - go_gc_*
    - type: logs
      provider: file
      paths:
        - /var/log/app/*.log
      parseFormat: json
      multilinePattern: '^\d{4}-\d{2}-\d{2}'
    - type: lokiQuery
      provider: loki
      loki:
        url: http://loki:3100
      queries:
        - expr: '{app="myapp"} |= "ERROR"'
          step: 15s
          rangeMinutes: 2
          limit: 4000
          interval: 60s
        - expr: '{namespace="prod"}'
          step: 30s
          rangeMinutes: 5
          limit: 8000
          interval: 120s

  # Optional sections (uncomment and configure if needed)
  # storage:
  #   s3:
  #     bucket: cloudsensei-observability
  #     region: eu-central-1
  #     prefix: raw
  #     compression: gzip
  #     credentialsSecretRef:
  #       name: cloudsensei-s3-creds
  #       accessKeyIdKey: access_key_id
  #       secretAccessKeyKey: secret_access_key
  # database:
  #   postgres:
  #     dsnSecretRef:
  #       name: cloudsensei-pg
  #       key: dsn
  # batching:
  #   maxBatchSize: 1000
  #   flushInterval: 15s
  #   compression: gzip
